# Generated by Django 4.2 on 2024-01-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consult_app', '0002_consultation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consult_app.address'),
        ),
    ]
